name: build

on:
  push:
  pull_request:
  schedule:
    - cron: '51 3 * * 6'  # Runs at 03:51, only on Saturday
jobs:
  build:
    name: ${{ matrix.os }}
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: ["ubuntu"]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: crystal-lang/install-crystal@v1
        with:
          crystal: latest
      - name: Download onnxruntime
        run: |
          wget https://github.com/microsoft/onnxruntime/releases/download/v1.20.1/onnxruntime-linux-x64-1.20.1.tgz
          tar -xvzf onnxruntime-linux-x64-1.20.1.tgz
      - name: Install dependencies
        run: shards install --without-development --release
      - name: Test
        env:
          ONNXRUNTIMEDIR: "/home/runner/work/onnxruntime.cr/onnxruntime.cr/onnxruntime-linux-x64-1.20.1"
        run: |
          crystal spec
